[ensemble]
ne = 50
state = ["injbhp"]
prior_injbhp = [
    ["mean", "init_injbhp.npz", ],
    ["var", 6250.0, ],
    ["limits", 1.0, 300.0, ],
]
transform = true

[optim]
maxiter = 10
tol = 1e-06
alpha = 0.25
alpha_maxiter = 3
resample = 0
optimizer = 'GA'
restartsave = true
restart = false
hessian = false
savedata = [
    "alpha",
    "obj_func_values",
]

[fwdsim]
npv_const = [
    ["wop", 300.0, ],
    ["wgp", 0.1, ],
    ["wwp", 40.0, ],
    ["wwi", 40.0, ],
    ["disc", 0.1, ],
    ["obj_scaling", -1.0e8, ],
]
parallel = 5
simoptions = ['sim_flag', '--tolerance-mb=1e-5']
runfile = "OPTIM_BHP"
reportpoint = 'report_dates.csv'
reporttype = "dates"
datatype = [
    "fopt",
    "fgpt",
    "fwpt",
    "fwit",
]
