[ensemble]
ne = 10
num_models = 5
state = [
    "injbhp",
    "prodbhp",
]
prior_injbhp = [
    [
        "mean",
        "init_injbhp.npz",
    ],
    [
        "var",
        6250.0,
    ],
    [
        "limits",
        200.0,
        400.0,
    ],
]
prior_prodbhp = [
    [
        "mean",
        "init_prodbhp.npz",
    ],
    [
        "var",
        6250.0,
    ],
    [
        "limits",
        100.0,
        200.0,
    ],
]
transform = true

[optim]
maxiter = 15
tol = 1e-03
alpha = 0.5
alpha_maxiter = 2
resample = 0
optimizer = 'GA'
restartsave = true
restart = false
hessian = true
savedata = [
    "alpha",
    "obj_func_values",
]

[fwdsim]
npv_const = [
    [
        "wop",
        283.05,
    ],
    [
        "wgp",
        0.0,
    ],
    [
        "wwp",
        37.74,
    ],
    [
        "wwi",
        12.58,
    ],
    [
        "disc",
        0.08,
    ],
    [
        "obj_scaling",
        -1.0e6,
    ],
]
parallel = 5
runfile = "3WELL_BHP"
reportpoint = 'report_dates.csv'
reporttype = "dates"
datatype = [
    "fopt",
    "fgpt",
    "fwpt",
    "fwit",
]
