[dataassim]
daalg = ["esmda", "esmda"]
analysis = "full"
energy = 95.0
obsname = "position"
ne = 250.0
truedataindex = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
                 90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145]
truedata = "true_data.csv"
assimindex = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
              16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]
state = "permx"
datavar = "var.csv"
prior_permx = [["vario", "sph"], ["mean", "priormean.npz"], ["var", 1.0], ["range", 20.0],
               ["aniso", 1.0], ["angle", 0.0], ["grid", [150.0, 1.0]]]
mda = [ ["tot_assim_steps", 3], ['inflation_param', [2, 4, 4]] ]

[fwdsim]
reporttype = "position"
reportpoint = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
               85, 90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145]
simulator = ["simple_models", "lin_1d"]
datatype = ["value"]
parallel = 4
