[ensemble]
ne = 10
state = [
    "vector",
]
prior_vector= [
    [
        "mean",
        "init_mean.npz",
    ],
    [
        "var",
        1.0e-5,
    ],
    [
        "limits",
        -2.0,
        2.0,
    ],
]
datatype = [
    "value",
]
transform = true

[optim]
maxiter = 500
tol = 1e-08
alpha = 0.25
alpha_maxiter = 8
resample = 0
optimizer = 'GA'
restartsave = true
restart = false
hessian = false
savedata = [
    "alpha",
    "obj_func_values",
]

[fwdsim]
parallel = 5
datatype = [
    "value",
]
