[dataassim]
daalg = [
    "es",
    "es",
]
analysis = "approx"
energy = 98.0
obsvarsave = "yes"
restartsave = "no"
analysisdebug = [
    "pred_data",
    "state",
    "data_misfit",
    "prev_data_misfit",
]
restart = "no"
obsname = "days"
ne = 64.0
truedataindex = [
    400,
    800,
    1200,
    1600,
    2000,
    2400,
    2800,
    3200,
    3600,
    4000,
]
truedata = "../data/true_data.csv"
assimindex = [
    [
        0,
    ],
    [
        1,
    ],
    [
        2,
    ],
    [
        3,
    ],
    [
        4,
    ],
    [
        5,
    ],
    [
        6,
    ],
    [
        7,
    ],
    [
        8,
    ],
    [
        9,
    ],
]
datatype = [
    "WOPR PRO1",
    "WOPR PRO2",
    "WOPR PRO3",
    "WWPR PRO1",
    "WWPR PRO2",
    "WWPR PRO3",
    "WWIR INJ1",
    "WWIR INJ2",
    "WWIR INJ3",
    "bulkimp",
]
staticvar = "permx"
state = "permx"
datavar = "../data/var.csv"
prior_permx = [
    [
        "vario",
        "sph",
    ],
    [
        "mean",
        "priormean.npz",
    ],
    [
        "var",
        1.0,
    ],
    [
        "range",
        10.0,
    ],
    [
        "aniso",
        1.0,
    ],
    [
        "angle",
        0.0,
    ],
    [
        "grid",
        [
            60.0,
            60.0,
            5.0,
        ],
    ],
]
compress = [
    [
        "field",
        [
            60.0,
            60.0,
            5.0,
        ],
    ],
    [
        "actnum",
        "actnum.npz",
        "actnum.npz",
    ],
    [
        "level",
        1.0,
    ],
    [
        "wname",
        "db2",
    ],
    [
        "cn",
        "no",
    ],
    [
        "threshold_rule",
        "universal",
    ],
    [
        "th_mult",
        10000.0,
    ],
    [
        "use_hard_th",
        "yes",
    ],
    [
        "keep_ca",
        "no",
    ],
    [
        "imp_inactive",
        0.0,
    ],
    [
        "use_ensemble",
        "yes",
    ],
    [
        "data_order",
        "c",
    ],
    [
        "min_noise",
        [
            1e-09,
            1e-09,
        ],
    ],
]
post_process_forecast = "yes"

[fwdsim]
reporttype = "days"
reportpoint = [
    400,
    800,
    1200,
    1600,
    2000,
    2400,
    2800,
    3200,
    3600,
    4000,
]
replace = "yes"
saveforecast = "yes"
sim_limit = 300.0
pem = [
    [
        "model",
        "standardrp elasticproperties",
    ],
    [
        "baseline",
        0.0,
    ],
    [
        "vintage",
        [
            2000.0,
            4000.0,
        ],
    ],
    [
        "overburden",
        "overburden.npz",
    ],
]
rerun = 1.0
runfile = "runfile"
datatype = [
    "WOPR PRO1",
    "WOPR PRO2",
    "WOPR PRO3",
    "WWPR PRO1",
    "WWPR PRO2",
    "WWPR PRO3",
    "WWIR INJ1",
    "WWIR INJ2",
    "WWIR INJ3",
    "bulkimp",
]
parallel = 8.0
startdate = "1/1/2022"
